services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  apiratelimiter1:
    container_name: apiratelimiter1
    depends_on:
      - redis
      - rabbitmq
    image: gitegob/apiratelimiter:latest
    environment:
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - 3001:3000
  apiratelimiter2:
    container_name: apiratelimiter2
    depends_on:
      - redis
      - rabbitmq
    image: gitegob/apiratelimiter:latest
    environment:
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - 3002:3000

  notification-api1:
    container_name: notification-api1
    depends_on:
      - rabbitmq
    image: gitegob/notification-api:latest
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - 4001:4000
  notification-api2:
    container_name: notification-api2
    depends_on:
      - rabbitmq
    image: gitegob/notification-api:latest
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - 4002:4000

  # postgres:
  #   container_name: postgres
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  redis_data:
  rabbitmq_data:
