services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  apiratelimiter1:
    container_name: apiratelimiter1
    depends_on:
      - redis
      - rabbitmq
    build: ./rate-limiter
    environment:
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      THROTTLE_TTL: "60"
      THROTTLE_LIMIT: "80"
      EUREKA_HOST: eureka
      EUREKA_PORT: "8761"
    ports:
      - 3000:3000
    restart: on-failure
  notification-api1:
    container_name: notification-api1
    depends_on:
      - rabbitmq
    build: ./notification-api
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      EUREKA_HOST: eureka
      EUREKA_PORT: "8761"
    ports:
      - 4000:4000
    restart: on-failure

  # postgres:
  #   container_name: postgres
  #   image: postgres:14-alpine
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:3000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure

  eureka:
    container_name: eureka
    build: ./eureka
    ports:
      - 8761:8761
    restart: on-failure
    # command: --eureka.instance.hostname=eureka --eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

volumes:
  redis_data:
  rabbitmq_data:
  postgres_data:
