services:
  eureka:
    container_name: eureka
    build: ./eureka
    ports:
      - 8761:8761
    restart: on-failure
    # command: --eureka.instance.hostname=host.docker.internal --eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
